//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch_Day
    {
        public int Id { get; set; }
        public System.DateTime StartingTime { get; set; }
        public System.DateTime EndingTime { get; set; }
        public int BranchID { get; set; }
        public int DayID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Day Day { get; set; }
    }
}
