//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Branch_Day = new HashSet<Branch_Day>();
            this.Branch_Item = new HashSet<Branch_Item>();
            this.Postcodes = new HashSet<Postcode>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public int ResturantID { get; set; }
    
        public virtual ICollection<Branch_Day> Branch_Day { get; set; }
        public virtual ICollection<Branch_Item> Branch_Item { get; set; }
        public virtual ResturantDetail ResturantDetail { get; set; }
        public virtual ICollection<Postcode> Postcodes { get; set; }
    }
}
