//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Discounts = new HashSet<Discount>();
            this.SpecialOffer_Item = new HashSet<SpecialOffer_Item>();
            this.Foods = new HashSet<Food>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CousineId { get; set; }
    
        public virtual Cousine Cousine { get; set; }
        public virtual ICollection<Discount> Discounts { get; set; }
        public virtual ICollection<SpecialOffer_Item> SpecialOffer_Item { get; set; }
        public virtual ICollection<Food> Foods { get; set; }
    }
}
