//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public Discount()
        {
            this.Order_Discount = new HashSet<Order_Discount>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Percentage { get; set; }
        public System.DateTime StartingDate { get; set; }
        public System.DateTime EndingDate { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.TimeSpan> StartingTime { get; set; }
        public Nullable<System.TimeSpan> EndingTime { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Order_Discount> Order_Discount { get; set; }
    }
}
