//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraCharge
    {
        public ExtraCharge()
        {
            this.Order_ExtraCharges = new HashSet<Order_ExtraCharges>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public Nullable<int> Minimum_Amount { get; set; }
        public Nullable<int> Maximum_Amount { get; set; }
        public int IsAvailable { get; set; }
    
        public virtual ICollection<Order_ExtraCharges> Order_ExtraCharges { get; set; }
    }
}
