//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public FoodItem()
        {
            this.Order_FoodItem = new HashSet<Order_FoodItem>();
            this.Order_SpecialOffer_FoodItem = new HashSet<Order_SpecialOffer_FoodItem>();
            this.Order_SpecialOffer_Item = new HashSet<Order_SpecialOffer_Item>();
            this.FoodItem_AddOn = new HashSet<FoodItem_AddOn>();
        }
    
        public int Id { get; set; }
        public string Size { get; set; }
        public double Price { get; set; }
        public int FoodId { get; set; }
        public Nullable<int> Food_Size_Id { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Food_Size Food_Size { get; set; }
        public virtual ICollection<Order_FoodItem> Order_FoodItem { get; set; }
        public virtual ICollection<Order_SpecialOffer_FoodItem> Order_SpecialOffer_FoodItem { get; set; }
        public virtual ICollection<Order_SpecialOffer_Item> Order_SpecialOffer_Item { get; set; }
        public virtual ICollection<FoodItem_AddOn> FoodItem_AddOn { get; set; }
    }
}
