//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Size
    {
        public Food_Size()
        {
            this.FoodItems = new HashSet<FoodItem>();
            this.SpecialOffer_Item = new HashSet<SpecialOffer_Item>();
            this.Food_AddOn = new HashSet<Food_AddOn>();
        }
    
        public int Id { get; set; }
        public string SizeDescription { get; set; }
    
        public virtual ICollection<FoodItem> FoodItems { get; set; }
        public virtual ICollection<SpecialOffer_Item> SpecialOffer_Item { get; set; }
        public virtual ICollection<Food_AddOn> Food_AddOn { get; set; }
    }
}
