//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_AddOn
    {
        public int Id { get; set; }
        public int FoodId { get; set; }
        public int AddOnId { get; set; }
        public Nullable<int> FoodSizeId { get; set; }
    
        public virtual AddOn AddOn { get; set; }
        public virtual Food Food { get; set; }
        public virtual Food_Size Food_Size { get; set; }
    }
}
