//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.Food_AddOn = new HashSet<Food_AddOn>();
            this.Food_Ingredients = new HashSet<Food_Ingredients>();
            this.FoodItems = new HashSet<FoodItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tageline { get; set; }
        public string Image { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Food_AddOn> Food_AddOn { get; set; }
        public virtual ICollection<Food_Ingredients> Food_Ingredients { get; set; }
        public virtual ICollection<FoodItem> FoodItems { get; set; }
    }
}
