//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Discount = new HashSet<Order_Discount>();
            this.Order_ExtraCharges = new HashSet<Order_ExtraCharges>();
            this.Order_Item = new HashSet<Order_Item>();
            this.Order_SpecialOffer = new HashSet<Order_SpecialOffer>();
            this.Order_Taxes = new HashSet<Order_Taxes>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Order_Discount> Order_Discount { get; set; }
        public virtual ICollection<Order_ExtraCharges> Order_ExtraCharges { get; set; }
        public virtual ICollection<Order_Item> Order_Item { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual ICollection<Order_SpecialOffer> Order_SpecialOffer { get; set; }
        public virtual ICollection<Order_Taxes> Order_Taxes { get; set; }
    }
}
