//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_SpecialOffer_FoodItem
    {
        public Order_SpecialOffer_FoodItem()
        {
            this.Order_SpecialOffer_AddOn = new HashSet<Order_SpecialOffer_AddOn>();
        }
    
        public int Id { get; set; }
        public int FoodItemId { get; set; }
        public int Order_SpecialOfferId { get; set; }
    
        public virtual FoodItem FoodItem { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<Order_SpecialOffer_AddOn> Order_SpecialOffer_AddOn { get; set; }
    }
}
