//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Taxes
    {
        public int Id { get; set; }
        public int OrderID { get; set; }
        public int TaxesID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Tax Tax { get; set; }
    }
}
