//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_SpecialOffer_AddOn
    {
        public int Id { get; set; }
        public int SpecialOffer_AddOnId { get; set; }
        public int Order_SpecialOfferId { get; set; }
    
        public virtual Order_SpecialOffer Order_SpecialOffer { get; set; }
        public virtual SpecialOffer_AddOn SpecialOffer_AddOn { get; set; }
    }
}
