//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_AddOn
    {
        public int Id { get; set; }
        public int Order_ItemId { get; set; }
        public int AddOnId { get; set; }
        public int CountofAddOn { get; set; }
    
        public virtual AddOn AddOn { get; set; }
        public virtual Order_Item Order_Item { get; set; }
    }
}
