//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item
    {
        public Order_Item()
        {
            this.OrderItem_AddOn = new HashSet<OrderItem_AddOn>();
        }
    
        public int Id { get; set; }
        public int OrderID { get; set; }
        public int FoodItemId { get; set; }
        public int Count { get; set; }
    
        public virtual FoodItem FoodItem { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderItem_AddOn> OrderItem_AddOn { get; set; }
    }
}
