//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_SpecialOffer_AddOn
    {
        public int Id { get; set; }
        public int AddOnid { get; set; }
        public int Order_SpecialOfferFoodItemId { get; set; }
    
        public virtual AddOn AddOn { get; set; }
        public virtual Order_SpecialOffer_FoodItem Order_SpecialOffer_FoodItem { get; set; }
    }
}
