//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialOffer_Item
    {
        public SpecialOffer_Item()
        {
            this.Order_SpecialOffer_Item = new HashSet<Order_SpecialOffer_Item>();
        }
    
        public int Id { get; set; }
        public int SpecialOfferID { get; set; }
        public int CategoryId { get; set; }
        public int SizeId { get; set; }
        public int Quantity { get; set; }
        public int isFlexible { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Food_Size Food_Size { get; set; }
        public virtual ICollection<Order_SpecialOffer_Item> Order_SpecialOffer_Item { get; set; }
        public virtual SpecialOffer SpecialOffer { get; set; }
    }
}
